config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.login.views import *
from core.user.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import *
from core.erp.views.proyecto.views import *
from core.erp.views.poste.views import *
from core.erp.views.proveedor.views import *
from core.erp.views.diseno.views import *

app_name = 'erp'

urlpatterns = [   
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    #poste
    path('poste/list/', PosteListView.as_view(), name='poste_list'),
    path('poste/add/', PosteCreateView.as_view(), name='poste_create'),
    path('poste/update/<str:pk>/', PosteUpdateView.as_view(), name='poste_update'),
    path('poste/delete/<str:pk>/', PosteDeleteView.as_view(), name='poste_delete'),
    
    #proyectos
    path('proyecto/list/', ProyectoListView.as_view(), name='proyecto_list'),
    path('proyecto/add/', ProyectoCreateView.as_view(), name='proyecto_create'),
    path('proyecto/update/<str:pk>/', ProyectoUpdateView.as_view(), name='proyecto_update'),
    path('proyecto/delete/<str:pk>/', ProyectoDeleteView.as_view(), name='proyecto_delete'),

    #proveedor
    path('prov/list/', ProveedorListView.as_view(), name='proveedor_list'),
    path('prov/add/', ProveedorCreateView.as_view(), name='proveedor_create'),
    path('prov/update/<str:pk>/', ProveedorUpdateView.as_view(), name='proveedor_update'),
    path('prov/delete/<str:pk>/', ProveedorDeleteView.as_view(), name='proveedor_delete'),

    #diseño
    path('diseno/list/', DisenoListView.as_view(), name='diseno_list'),
    path('diseno/add/', DisenoCreateView.as_view(), name='diseno_create'),
    path('diseno/update/<str:pk>/', DisenoUpdateView.as_view(), name='diseno_update'),
    path('diseno/delete/<str:pk>/', DisenoDeleteView.as_view(), name='diseno_delete'),

    

]

core/user/urls.py
from django.urls import path
from core.user.views import *


app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('password/', UserPasswordView.as_view(), name='user_password'),

]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <style>
            .navbar-expand {
                background: #000f2e !important;
            }
        </style>
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Inicio</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">

        {% if request.user.groups.all %}
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
               class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
            {% if request.user.groups.all.count > 1 %}
                <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                    style="left: 0px; right: inherit;">
                    {% for g in request.user.groups.all %}
                        {% if g.id != request.session.group.id %}
                            <li><a href="{% url 'user:user_change_group' g.id %}"
                                   class="dropdown-item">{{ g.name }} </a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header" style="font-size: 12px;">
                    Sú último acceso fue {{ request.user.last_login }}
                </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_password' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar contraseña
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-blue elevation-4">
    <style>
        .sidebar-dark-blue{
          background: #000f2e !important;
        }
        .main-sidebar * {
            color: #ffffff !important;
        }
   </style>
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
        <img src="{% static 'img/fasbas.png' %}"
             alt="Logo"
             class="brand-image   elevation-3"
             style="opacity: 1">
        <span class="brand-text font-weight-light">FasBas</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Módulos</li>

                

            
                <li class="nav-item">
                    <a href="{% url 'erp:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Inicio
                        </p>
                    </a>
                </li>
              
                <li class="nav-item">
                    <a href="{% url 'erp:poste_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Poste
                        </p>
                    </a>
                </li>
                
                <li class="nav-item"></li>
                    <a href="{% url 'erp:proyecto_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Proyectos
                        </p>
                    </a>
                </li>

                <li class="nav-item"></li>
                    <a href="{% url 'erp:diseno_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Propuesta de diseño
                        </p>
                    </a>
                </li>


             
              
             
                <li class="nav-item">
                    <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-solid fa-chart-line"></i>
                    <p>
                    Reportes
                    <i class="fas fa-angle-left right"></i>
                    
                    </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                    <a href="{% url 'postes_report'%}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Postes</p>
                    </a>
                    </li>
                    
                    <li class="nav-item">
                    <a href="" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Entrega de proyecto</p>
                    </a>
                    </li>
                    
                  
                    </ul>
                    </li>





                

                <hr>
                                        
                        <li class="nav-item">
                            <a href="{% url 'erp:proveedor_list' %}" class="nav-link">
                                <i class="fas fa-tags"></i>
                                <p>Competidores</p>
                            </a>
                        </li>
                
                        
                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="nav-link">
                                <i class="fas fa-user-friends"></i>
                                <p>Usuarios</p>
                            </a>
                        </li>

                    </u>

        </nav>
    </div>
</aside>